version: '3'

services:
  monade_web:
    build: .
    env_file: .env
    environment:
      MYENV: venv
    volumes:
      - .:/code
    command: >
      sh -c "python3 manage.py migrate --noinput &&
             python3 manage.py collectstatic --noinput &&
             chown -R www-data:www-data /code/medias /code/static_root &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8013:8000"
    restart: unless-stopped
    depends_on:
      - monade_db

  monade_db:
    image: postgres:14
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - "127.0.0.1:8014:5432"

volumes:
  db: