web:
  build: .
  environment:
    MYENV: venv
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: python /code/manage.py migrate
web_run:
  extends:
    service: web
  command: python /code/manage.py runserver 0.0.0.0:8000
  ports:
    - "0.0.0.0:8000:8000"