# Generated by Django 4.2.3 on 2023-07-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_folder', models.TextField(verbose_name='Project folder')),
                ('shp_file', models.FileField(upload_to='', verbose_name='Shp File')),
                ('dbf_file', models.FileField(upload_to='', verbose_name='Dbf File')),
                ('shx_file', models.FileField(upload_to='', verbose_name='Shx File')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploads/constraints', verbose_name='File')),
                ('minimun', models.FloatField(verbose_name='Minimum')),
                ('maximun', models.FloatField(verbose_name='Maximum')),
                ('user_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userdata')),
            ],
        ),
    ]
