# Generated by Django 4.2.3 on 2023-07-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constraint',
            old_name='file_path',
            new_name='file',
        ),
    ]
