# Generated by Django 4.2.3 on 2023-07-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_file_path_constraint_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constraint',
            old_name='maximun',
            new_name='maximum',
        ),
        migrations.RenameField(
            model_name='constraint',
            old_name='minimun',
            new_name='minimum',
        ),
    ]
