# Generated by Django 4.2.3 on 2023-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_maximun_constraint_maximum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cell_size',
            field=models.FloatField(default=0, verbose_name='Cell size'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='travel_speed',
            field=models.FloatField(default=0, verbose_name='Travel speed (km/time step)'),
        ),
    ]
