# Generated by Django 4.2.3 on 2023-08-06 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_userdata_cell_size_userdata_travel_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shp_file', models.FileField(upload_to=web.models.get_request_shapefile_upload_path, verbose_name='Shp File')),
                ('dbf_file', models.FileField(upload_to=web.models.get_request_shapefile_upload_path, verbose_name='Dbf File')),
                ('shx_file', models.FileField(upload_to=web.models.get_request_shapefile_upload_path, verbose_name='Shx File')),
                ('travel_speed', models.FloatField(default=0, verbose_name='Travel speed (km/time step)')),
                ('cell_size', models.FloatField(default=0, verbose_name='Cell size')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='user_data_id',
        ),
        migrations.AlterField(
            model_name='constraint',
            name='file',
            field=models.FileField(upload_to=web.models.get_request_constraint_upload_path, verbose_name='File'),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='request',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.request', verbose_name='Request'),
        ),
    ]
