# Generated by Django 4.2.3 on 2023-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_request_workspace_remove_constraint_user_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='req_uid',
            field=models.CharField(default='', max_length=255, verbose_name='Unique ID'),
        ),
    ]
