# Generated by Django 4.2.3 on 2023-08-06 19:59

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_request_req_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='affected_area',
            field=models.FileField(default=False, upload_to=web.models.get_request_affarea_upload_path, verbose_name='Shx File'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dbf_file',
            field=models.FileField(default=False, upload_to=web.models.get_request_shapefile_upload_path, verbose_name='Dbf File'),
        ),
        migrations.AlterField(
            model_name='request',
            name='shp_file',
            field=models.FileField(default=False, upload_to=web.models.get_request_shapefile_upload_path, verbose_name='Shp File'),
        ),
        migrations.AlterField(
            model_name='request',
            name='shx_file',
            field=models.FileField(default=False, upload_to=web.models.get_request_shapefile_upload_path, verbose_name='Shx File'),
        ),
        migrations.AlterField(
            model_name='request',
            name='workspace',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='web.workspace', verbose_name='Workspace'),
        ),
    ]
