# Generated by Django 4.2.3 on 2023-08-06 21:54

from django.db import migrations, models
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_request_affected_area_alter_request_dbf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='request',
            name='affected_area',
            field=models.FileField(default=False, upload_to=web.models.get_request_affarea_upload_path, verbose_name='Affected area'),
        ),
    ]
