# Generated by Django 3.2 on 2023-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230523_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Full Name'),
        ),
    ]
