# Generated by Django 3.2 on 2023-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
